name: Deploy website

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - name: Install Yarn
        run: npm i -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Build the website
        run: yarn build
      - name: Deploy to GitHub Pages
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: dist
          GH_PAT: ${{ secrets.GH_PAT }}
